print(.libPaths())
repo = "http://cran.us.r-project.org"

install.packages("ggrepel", repos=repo)
install.packages("cowplot", repos=repo)
install.packages("ggplot2", repos=repo)
install.packages("dplyr", repos=repo)
install.packages("tibble", repos=repo)
install.packages("data.table", repos=repo)
install.packages("here", repos=repo)
install.packages("UpSetR", repos=repo)
install.packages("umap", repos=repo)
install.packages("tableHTML", repos=repo)
install.packages("pheatmap", repos=repo)
install.packages("viridis", repos=repo)
install.packages("reshape", repos=repo)

install.packages("Rcpp", repos=repo)
install.packages("shiny", repos=repo)
install.packages("shinydashboard", repos=repo)
install.packages("shinyWidgets", repos=repo)
install.packages("shinyjs", repos=repo)
install.packages("qdap", repos=repo)
install.packages("plotly", repos=repo)
install.packages("Dict", repos=repo)
install.packages("paletteer", repos=repo)

install.packages("BiocManager", repos=repo)
BiocManager::install("SummarizedExperiment", force=TRUE)

install.packages("Cairo", repos=repo)
install.packages("doParallel", repos=repo)
BiocManager::install("DEP", force=TRUE)
BiocManager::install("biomaRt", force=TRUE)

install.packages("devtools", repos=repo)
library(devtools)
install_github("vqv/ggbiplot")
install_github("Laurae2/Laurae")
install_github(repo = "hhoeflin/hdf5r")
install_github(repo = "mojaveazure/loomR", ref = "develop")

install.packages("ncdf4",repos = repo)
install.packages("imputeLCMD",repos = repo)
